name: flake8  # name of the action

on:
   # Trigger the workflow on push or pull request,
   # but only for the master branch
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

jobs:  # note that each job is run on a different runner
  flake8:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2  #  use script at github action market
    # place to pull project to local machine, and checkout to branch

    - name: Set up Python 3.9
      uses: actions/setup-python@v1  # another github action market script
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install flake8

    - name: Lint with flake8
      run: |
        flake8 .
